### PR TITLE
Add MergeCell

### PR DESCRIPTION
**Pull request by JoJeongMin**
Why do you want to add 
- there is no merge function of cell.

Example
- Merge Cell A1:C5

```
        $xlsx->setValue('(記入日　'.\Cake\I18n\FrozenDate::today().')', [
            'col' => 'A',
            'row' => 1,
            'mergeCell' => [
                'col' => 'C',
                'row' => 5,
           ]
            'border' => [
                'left' => PHPExcel_Style_Border::BORDER_THIN,
                'right' => PHPExcel_Style_Border::BORDER_THIN,
                'bottom' => PHPExcel_Style_Border::BORDER_THIN,
            ],
        ]);
```

### CODE REVIEW

**Comment by JoJeongMin** [comment]
@k1LoW I rewrite some text in English. I would like to review this PR.

**Comment by k1LoW** [comment]
@JoJeongMin 
Thank you for your contribution! Nice idea!

I think it is better to divide the `set value` and `merge cells`.

like this.

``` php
<?php
$xlsx->setValue('(記入日　'.\Cake\I18n\FrozenDate::today().')', [
    'col' => 'A',
    'row' => 1,
])->mergeCells([
    'col' => 'A', // or fromCol
    'row' => 1, // or fromRow
    'toCol' => 'C',
    'toRow' => 5,
    'border' => [
         'left' => PHPExcel_Style_Border::BORDER_THIN,
         'right' => PHPExcel_Style_Border::BORDER_THIN,
         'bottom' => PHPExcel_Style_Border::BORDER_THIN,
    ],
]);
```

What do you think of my idea?

**Comment by k1LoW** [comment]
And `s/mergeCell/mergeCells/`

**Comment by JoJeongMin** [comment]
@k1LoW 
Thank you for your advice .
Failed to that thought .
I will modify it as advice .

**Comment by JoJeongMin** [comment]
@k1LoW 
Development was completed .
Please review .

**Comment by k1LoW** [comment]
Thank you for your great commit!!! LGTM!
@JoJeongMin

**Pull request merged**
